"""generate CLI (FR-G1-G4): trace -> journey plan -> flow.py + scan config.

The LLM emits a constrained JSON journey plan (validated against journey.schema.json);
deterministic code renders it into flow.py — the LLM never authors executable code (safety).
LLM is the primary path (Anthropic SDK, ANTHROPIC_API_KEY); a deterministic trace->plan
fallback is used only if the key is absent or the model output can't be repaired.

Deterministic transforms (emit_scope / render_flow / emit_*) are pure and unit-tested; the
live LLM call is verified by running it with a key.
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
from pathlib import Path

import jsonschema

from runner.scope_guard import host_of

_ROOT = Path(__file__).resolve().parent.parent
_JOURNEY_SCHEMA = _ROOT / "contracts" / "journey.schema.json"
_SCOPE_SCHEMA = _ROOT / "contracts" / "scope.schema.json"
_VERSIONS_LOCK = _ROOT / "versions.lock"

_DEFAULT_MODEL = "claude-sonnet-5"
_DEFAULT_TOKEN_CHECK = "window.localStorage.getItem('token')"


def _relpath(url: str, base_url: str) -> str:
    if url.startswith(base_url):
        return url[len(base_url):] or "/"
    return url if url.startswith("/") else ""


# ---- FR-G2: scope emission --------------------------------------------------------------

def emit_scope(trace: dict) -> dict:
    hosts = list(trace.get("hosts") or [])
    target = host_of(trace["base_url"]) or (hosts[0] if hosts else "localhost")
    allow = sorted(set(hosts) | {target})
    return {
        "app_id": trace["app_id"],
        "environment_class": "dev",
        "target_fqdn": target,
        "fqdn_allow_list": allow,
        "fqdn_deny_list": ["*.google-analytics.com"],
        "avoid_action_list": ["logout", "delete-account"],
    }


# ---- journey plan: deterministic fallback + validation ----------------------------------

def journey_from_trace(trace: dict) -> dict:
    base = trace["base_url"]
    login = {
        "url": "/#/login",
        "email_selector": "#email",
        "password_selector": "#password",
        "submit_selector": "#loginButton",
        "token_check": _DEFAULT_TOKEN_CHECK,
    }
    journey: list[dict] = []
    for route in trace.get("index", []):
        path = _relpath(route, base)
        if path and "/login" not in path and path not in ("/#/", "/"):
            journey.append({"action": "goto", "target": path})
    for a in trace.get("api", []):
        if a.get("method", "GET").upper() == "GET":
            path = _relpath(a["url"], base)
            if path:
                journey.append({"action": "api_get", "target": path})
    if not journey:
        journey = [{"action": "goto", "target": "/#/"}]
    seen, dedup = set(), []
    for s in journey:
        key = (s["action"], s["target"])
        if key not in seen:
            seen.add(key)
            dedup.append(s)
    return {"app_id": trace["app_id"], "base_url": base, "login": login, "journey": dedup}


def validate_plan(plan: dict) -> None:
    """Raise jsonschema.ValidationError if the plan is not a valid journey."""
    jsonschema.validate(plan, json.loads(_JOURNEY_SCHEMA.read_text()))


def parse_plan_text(text: str) -> dict:
    """Extract a JSON object from raw LLM text (strips ``` fences). Raises ValueError."""
    t = text.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", t, re.DOTALL)
    if fence:
        t = fence.group(1).strip()
    start, end = t.find("{"), t.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError("no JSON object found in text")
    try:
        return json.loads(t[start:end + 1])
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON: {exc}") from exc


# ---- Step B: deterministic render (LLM safety boundary) ----------------------------------

def render_flow(plan: dict) -> str:
    """Render a validated journey plan into flow.py source. Deterministic (FR-G4); no secrets
    (creds from env, NFR-3). String literals are json.dumps-quoted for safety."""
    login = plan["login"]
    token_check = login.get("token_check") or _DEFAULT_TOKEN_CHECK
    out: list[str] = []
    w = out.append
    w('"""Generated by authoring/generate.py from a journey plan. Do not edit by hand."""')
    w("from __future__ import annotations")
    w("")
    w("import os")
    w("")
    w("")
    w("def _dismiss_banners(page):")
    w("    for sel in (\"button[aria-label='Close Welcome Banner']\", "
      "\"a[aria-label='dismiss cookie message']\", \".cc-btn\"):")
    w("        try:")
    w("            el = page.locator(sel)")
    w("            if el.count() and el.first.is_visible():")
    w("                el.first.click(timeout=2000)")
    w("        except Exception:")
    w("            pass")
    w("")
    w("")
    w("def run(page, base_url, evidence_dir=None):")
    w('    email = os.environ.get("AUTH_EMAIL", "")')
    w('    password = os.environ.get("AUTH_PASSWORD", "")')
    w(f'    page.goto(base_url + {json.dumps(login["url"])}, wait_until="networkidle")')
    w("    _dismiss_banners(page)")
    w(f'    page.fill({json.dumps(login["email_selector"])}, email)')
    w(f'    page.fill({json.dumps(login["password_selector"])}, password)')
    w(f'    page.click({json.dumps(login["submit_selector"])})')
    w(f'    page.wait_for_function({json.dumps("() => !!(" + token_check + ")")}, timeout=15000)')
    w(f'    token = page.evaluate({json.dumps("() => " + token_check)})')
    w("    if not token:")
    w('        raise RuntimeError("login did not produce an auth token")')
    for step in plan["journey"]:
        action, target = step["action"], step["target"]
        if action == "goto":
            w(f'    page.goto(base_url + {json.dumps(target)}, wait_until="networkidle")')
        elif action == "click":
            w(f'    page.click({json.dumps(target)})')
        elif action == "api_get":
            w(f'    page.request.get(base_url + {json.dumps(target)}, '
              'headers={"Authorization": f"Bearer {token}"})')
    w('    return {"authenticated": True, "token_present": bool(token)}')
    w("")
    return "\n".join(out)


# ---- FR-G3: policy / manifest / lock / auth ---------------------------------------------

def emit_zap_policy(intensity: str = "medium") -> dict:
    return {
        "intensity": intensity,
        "attack_strength": intensity,
        "alert_threshold": "medium",
        "disabled_scanners": ["40026"],  # DOM-XSS (browser-based) — too heavy, see runner
    }


def emit_manifest(trace: dict) -> dict:
    return {
        "app_id": trace["app_id"],
        "base_url": trace["base_url"],
        "generated_by": "authoring/generate.py",
        "artifacts": ["flow.py", "scope.json", "auth.json", "zap-policy.yaml",
                      "manifest.json", "lock"],
    }


def emit_lock() -> dict:
    lock: dict[str, str] = {}
    if _VERSIONS_LOCK.exists():
        for line in _VERSIONS_LOCK.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            k, v = line.split(":", 1)
            lock[k.strip()] = v.strip()
    lock.setdefault("playwright_version", "1.62.0")
    return lock


def emit_auth() -> dict:
    """auth.json references env var names for creds — never the secrets themselves (NFR-3)."""
    return {"email_env": "AUTH_EMAIL", "password_env": "AUTH_PASSWORD"}


# ---- Step A (primary): LLM plan ---------------------------------------------------------

def plan_from_llm(trace: dict, model: str, api_key: str) -> dict:
    """Ask the LLM for a journey plan (validated). Raises on any failure so callers can fall
    back. anthropic is imported lazily so the fallback/tests don't need it."""
    import anthropic  # lazy

    schema = _JOURNEY_SCHEMA.read_text()
    system = (
        "You convert a web-app crawl trace into a STRICT JSON 'journey plan' for an "
        "authenticated DAST scan. Output ONLY the JSON object — no prose, no code fences. "
        "It must validate against this JSON Schema:\n" + schema
    )
    user = (
        "Crawl trace (no secrets):\n" + json.dumps(trace, indent=2) +
        "\n\nProduce the journey plan: a login block (selectors) and a short authenticated "
        "journey (goto authenticated routes, api_get authenticated GET endpoints). "
        "Do not include credentials."
    )
    client = anthropic.Anthropic(api_key=api_key)
    msg = client.messages.create(
        model=model, max_tokens=2000, temperature=0,
        system=system, messages=[{"role": "user", "content": user}],
    )
    text = "".join(getattr(b, "text", "") for b in msg.content)
    plan = parse_plan_text(text)
    validate_plan(plan)  # raise if the model produced something off-contract
    return plan


def make_plan(trace: dict, use_llm: bool = True, model: str = _DEFAULT_MODEL,
              api_key: str | None = None) -> tuple[dict, str]:
    """Return (plan, source) where source is 'llm' or 'fallback'."""
    api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
    if use_llm and api_key:
        try:
            return plan_from_llm(trace, model, api_key), "llm"
        except Exception as exc:  # network/parse/validation — fall back deterministically
            print(f"generate: LLM path failed ({exc}); using deterministic fallback",
                  file=sys.stderr)
    plan = journey_from_trace(trace)
    validate_plan(plan)
    return plan, "fallback"


def generate(trace: dict, out_dir: str, use_llm: bool = True, model: str = _DEFAULT_MODEL,
             api_key: str | None = None) -> dict:
    """Produce all authoring artifacts from a trace. Returns a summary dict."""
    plan, source = make_plan(trace, use_llm=use_llm, model=model, api_key=api_key)
    flow_src = render_flow(plan)
    ast.parse(flow_src)  # guarantee the generated code compiles (FR-G1 pre-check)

    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    (d / "journey.json").write_text(json.dumps(plan, indent=2) + "\n")
    (d / "flow.py").write_text(flow_src)
    (d / "scope.json").write_text(json.dumps(emit_scope(trace), indent=2) + "\n")
    (d / "auth.json").write_text(json.dumps(emit_auth(), indent=2) + "\n")
    # json.dumps is valid YAML, so no PyYAML dependency is needed for the .yaml file.
    (d / "zap-policy.yaml").write_text(json.dumps(emit_zap_policy(), indent=2) + "\n")
    (d / "manifest.json").write_text(json.dumps(emit_manifest(trace), indent=2) + "\n")
    (d / "lock").write_text(json.dumps(emit_lock(), indent=2) + "\n")
    return {"plan_source": source, "journey_steps": len(plan["journey"]), "out_dir": str(d)}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate flow.py + scan config from a trace (FR-G1-4).")
    p.add_argument("--trace", required=True, help="Path to trace.json from record")
    p.add_argument("--out-dir", required=True)
    p.add_argument("--model", default=_DEFAULT_MODEL)
    p.add_argument("--no-llm", action="store_true", help="Force the deterministic fallback plan")
    args = p.parse_args(argv)

    trace = json.loads(Path(args.trace).read_text())
    summary = generate(trace, args.out_dir, use_llm=not args.no_llm, model=args.model)
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
